### ISSUE TITLE
ssl error in the script

### ISSUE THREAD

**Issue by toddy** [chris34/UWR-calendar-script#1]
Now, ubuntuusers.de use https and I get an error by using this script.

Stracktrace: https://paste.ubuntuusers.de/421788/

OS: Ubuntu 14.04 LTS with Python 2.7.6

**Comment by chris34** [comment]
should be solved [after the mirgration to python3](https://github.com/chris34/UWR-calendar-script/commit/93f24078a17eed4953825d31f29533b9011e1bf7) (bug was caused by the ssl-library of the reported python-version)
